module.exports=[
    {
      city: "Tbilisi",
      lat: "41.7225",
      lng: "44.7925",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Tbilisi",
      capital: "primary",
      population: "1118035",
      population_proper: "1118035"
    },
    {
      city: "Batumi",
      lat: "41.6458",
      lng: "41.6417",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "admin",
      population: "169095",
      population_proper: "169095"
    },
    {
      city: "Kutaisi",
      lat: "42.2500",
      lng: "42.7000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "admin",
      population: "147900",
      population_proper: "147900"
    },
    {
      city: "Rustavi",
      lat: "41.5472",
      lng: "45.0111",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "admin",
      population: "128680",
      population_proper: "128680"
    },
    {
      city: "Sokhumi",
      lat: "43.0000",
      lng: "41.0167",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "admin",
      population: "64441",
      population_proper: "64441"
    },
    {
      city: "Gori",
      lat: "41.9817",
      lng: "44.1124",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "admin",
      population: "48143",
      population_proper: "44524"
    },
    {
      city: "Zugdidi",
      lat: "42.5083",
      lng: "41.8667",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "admin",
      population: "42998",
      population_proper: "41494"
    },
    {
      city: "Poti",
      lat: "42.1500",
      lng: "41.6667",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "41465",
      population_proper: "41465"
    },
    {
      city: "Tskhinvali",
      lat: "42.2257",
      lng: "43.9701",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "",
      population: "30432",
      population_proper: "30432"
    },
    {
      city: "Kobuleti",
      lat: "41.8111",
      lng: "41.7753",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "27546",
      population_proper: "27546"
    },
    {
      city: "Khashuri",
      lat: "41.9975",
      lng: "43.5986",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "minor",
      population: "26135",
      population_proper: "24601"
    },
    {
      city: "Samtredia",
      lat: "42.1625",
      lng: "42.3417",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "25318",
      population_proper: "6423"
    },
    {
      city: "Senaki",
      lat: "42.2689",
      lng: "42.0678",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "21596",
      population_proper: "21596"
    },
    {
      city: "Zestaponi",
      lat: "42.1083",
      lng: "43.0417",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "20814",
      population_proper: "20814"
    },
    {
      city: "Marneuli",
      lat: "41.4969",
      lng: "44.8108",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "20211",
      population_proper: "12400"
    },
    {
      city: "Telavi",
      lat: "41.9167",
      lng: "45.4833",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "admin",
      population: "19629",
      population_proper: "19509"
    },
    {
      city: "Gardabani",
      lat: "41.4500",
      lng: "45.1000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "15100",
      population_proper: "1846"
    },
    {
      city: "Ozurgeti",
      lat: "41.9406",
      lng: "41.9906",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "admin",
      population: "14785",
      population_proper: "844"
    },
    {
      city: "Akhaltsikhe",
      lat: "41.6389",
      lng: "42.9861",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "admin",
      population: "14000",
      population_proper: "10153"
    },
    {
      city: "Kaspi",
      lat: "41.9250",
      lng: "44.4222",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "minor",
      population: "13423",
      population_proper: "12708"
    },
    {
      city: "Chiatura",
      lat: "42.2903",
      lng: "43.2819",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "12803",
      population_proper: "12803"
    },
    {
      city: "Tsqaltubo",
      lat: "42.3264",
      lng: "42.6006",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "11281",
      population_proper: "3409"
    },
    {
      city: "Sagarejo",
      lat: "41.7333",
      lng: "45.3333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "10871",
      population_proper: "10871"
    },
    {
      city: "Borjomi",
      lat: "41.8389",
      lng: "43.3792",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "",
      population: "10546",
      population_proper: "3500"
    },
    {
      city: "T’q’ibuli",
      lat: "42.3503",
      lng: "42.9983",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "9770",
      population_proper: "1023"
    },
    {
      city: "Khoni",
      lat: "42.3244",
      lng: "42.4222",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "8987",
      population_proper: "8117"
    },
    {
      city: "Bolnisi",
      lat: "41.4500",
      lng: "44.5333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "8967",
      population_proper: "8967"
    },
    {
      city: "Akhalkalaki",
      lat: "41.4056",
      lng: "43.4861",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "minor",
      population: "8295",
      population_proper: "8295"
    },
    {
      city: "Gurjaani",
      lat: "41.7444",
      lng: "45.8000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "8024",
      population_proper: "4553"
    },
    {
      city: "Mtskheta",
      lat: "41.8464",
      lng: "44.7194",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "admin",
      population: "7940",
      population_proper: "7606"
    },
    {
      city: "Q’vareli",
      lat: "41.9500",
      lng: "45.8167",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "7739",
      population_proper: "5150"
    },
    {
      city: "Gali",
      lat: "42.6333",
      lng: "41.7333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "7605",
      population_proper: "7449"
    },
    {
      city: "Sadakhlo",
      lat: "41.2389",
      lng: "44.7878",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "7337",
      population_proper: "7337"
    },
    {
      city: "Q’izil-Ajlo",
      lat: "41.4786",
      lng: "44.7725",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "7291",
      population_proper: "7291"
    },
    {
      city: "Ts’q’neti",
      lat: "41.6950",
      lng: "44.6969",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Tbilisi",
      capital: "",
      population: "7166",
      population_proper: "7166"
    },
    {
      city: "Akhmeta",
      lat: "42.0333",
      lng: "45.2000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "7105",
      population_proper: "2114"
    },
    {
      city: "Chakvi",
      lat: "41.7189",
      lng: "41.7333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "",
      population: "6720",
      population_proper: "6720"
    },
    {
      city: "Lanchkhuti",
      lat: "42.0875",
      lng: "42.0361",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "minor",
      population: "6395",
      population_proper: "3069"
    },
    {
      city: "Dusheti",
      lat: "42.0845",
      lng: "44.6961",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "6167",
      population_proper: "6167"
    },
    {
      city: "Sachkhere",
      lat: "42.3389",
      lng: "43.4039",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "6140",
      population_proper: "2757"
    },
    {
      city: "Sartichala",
      lat: "41.7139",
      lng: "45.1725",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "6009",
      population_proper: "6009"
    },
    {
      city: "Dedoplists’q’aro",
      lat: "41.4652",
      lng: "46.1045",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "5940",
      population_proper: "4126"
    },
    {
      city: "Lagodekhi",
      lat: "41.8268",
      lng: "46.2767",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "minor",
      population: "5918",
      population_proper: "5918"
    },
    {
      city: "Baghdati",
      lat: "42.0678",
      lng: "42.8247",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "5465",
      population_proper: "5465"
    },
    {
      city: "Ochkhamuri",
      lat: "41.8553",
      lng: "41.8361",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "",
      population: "5355",
      population_proper: "5355"
    },
    {
      city: "Ochamchire",
      lat: "42.7100",
      lng: "41.4700",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "5280",
      population_proper: "5280"
    },
    {
      city: "Ninotsminda",
      lat: "41.2658",
      lng: "43.5889",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "",
      population: "5144",
      population_proper: "964"
    },
    {
      city: "T’q’varcheli",
      lat: "42.8500",
      lng: "41.6833",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "5097",
      population_proper: "5097"
    },
    {
      city: "Algeti",
      lat: "41.4481",
      lng: "44.8953",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "5017",
      population_proper: "5017"
    },
    {
      city: "Abasha",
      lat: "42.2042",
      lng: "42.2028",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "4941",
      population_proper: "1514"
    },
    {
      city: "Tsnori",
      lat: "41.6125",
      lng: "45.9736",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "4815",
      population_proper: "1789"
    },
    {
      city: "Terjola",
      lat: "42.1833",
      lng: "42.9772",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "4644",
      population_proper: "3995"
    },
    {
      city: "Martvili",
      lat: "42.4139",
      lng: "42.3778",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "4425",
      population_proper: "1660"
    },
    {
      city: "Khobi",
      lat: "42.3167",
      lng: "41.9000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "4242",
      population_proper: "342"
    },
    {
      city: "Bich’vinta",
      lat: "43.1667",
      lng: "40.3333",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "4198",
      population_proper: "4107"
    },
    {
      city: "Ingiri",
      lat: "42.4957",
      lng: "41.8085",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "4049",
      population_proper: "4049"
    },
    {
      city: "Tsalenjikha",
      lat: "42.6117",
      lng: "42.0706",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "3847",
      population_proper: "3170"
    },
    {
      city: "Norio",
      lat: "41.7883",
      lng: "44.9786",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "3756",
      population_proper: "3756"
    },
    {
      city: "Vani",
      lat: "42.0846",
      lng: "42.5034",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "3744",
      population_proper: "2691"
    },
    {
      city: "Sabirkendi",
      lat: "41.4514",
      lng: "44.8650",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "3403",
      population_proper: "3403"
    },
    {
      city: "Kvemo Nat’anebi",
      lat: "41.9378",
      lng: "41.8039",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "3099",
      population_proper: "3099"
    },
    {
      city: "Tetri Ts’q’aro",
      lat: "41.5500",
      lng: "44.4667",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "3093",
      population_proper: "3093"
    },
    {
      city: "Gonio",
      lat: "41.5597",
      lng: "41.5722",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "",
      population: "2886",
      population_proper: "2886"
    },
    {
      city: "Tsinandali",
      lat: "41.8947",
      lng: "45.5756",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "2675",
      population_proper: "2675"
    },
    {
      city: "Dmanisi",
      lat: "41.3317",
      lng: "44.2036",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "2661",
      population_proper: "1871"
    },
    {
      city: "Makho",
      lat: "41.5536",
      lng: "41.6706",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "",
      population: "2479",
      population_proper: "2479"
    },
    {
      city: "Tsikhisdziri",
      lat: "41.7619",
      lng: "41.7539",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "",
      population: "2472",
      population_proper: "2472"
    },
    {
      city: "Duisi",
      lat: "42.1456",
      lng: "45.2939",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "2354",
      population_proper: "2354"
    },
    {
      city: "Narazeni",
      lat: "42.4125",
      lng: "41.9461",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "2345",
      population_proper: "2345"
    },
    {
      city: "Tsalka",
      lat: "41.5983",
      lng: "44.0953",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "minor",
      population: "2326",
      population_proper: "1741"
    },
    {
      city: "Aghmamedlo",
      lat: "41.3300",
      lng: "44.9039",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "2289",
      population_proper: "2289"
    },
    {
      city: "Kondoli",
      lat: "41.9197",
      lng: "45.5781",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "2188",
      population_proper: "2188"
    },
    {
      city: "Zeda Sakara",
      lat: "42.1425",
      lng: "43.0664",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "2099",
      population_proper: "2099"
    },
    {
      city: "Ambrolauri",
      lat: "42.5194",
      lng: "43.1500",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Rach’a-Lechkhumi da Kvemo Svaneti",
      capital: "admin",
      population: "2047",
      population_proper: "2015"
    },
    {
      city: "Mukhaestate",
      lat: "41.8419",
      lng: "41.8664",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "",
      population: "2045",
      population_proper: "2045"
    },
    {
      city: "Kveda Sakara",
      lat: "42.1256",
      lng: "43.0311",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1989",
      population_proper: "1989"
    },
    {
      city: "Mestia",
      lat: "43.0456",
      lng: "42.7297",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "1973",
      population_proper: "1973"
    },
    {
      city: "Kharagauli",
      lat: "42.0167",
      lng: "43.2000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "minor",
      population: "1965",
      population_proper: "1965"
    },
    {
      city: "Kisiskhevi",
      lat: "41.8978",
      lng: "45.5436",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "1916",
      population_proper: "1916"
    },
    {
      city: "Chokhatauri",
      lat: "42.0189",
      lng: "42.2394",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "minor",
      population: "1815",
      population_proper: "903"
    },
    {
      city: "Akhaldaba",
      lat: "41.9303",
      lng: "43.4864",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "",
      population: "1800",
      population_proper: "1800"
    },
    {
      city: "Kulashi",
      lat: "42.2042",
      lng: "42.3456",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1702",
      population_proper: "1702"
    },
    {
      city: "Kvishkheti",
      lat: "41.9694",
      lng: "43.5014",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "",
      population: "1699",
      population_proper: "1699"
    },
    {
      city: "Pshaveli",
      lat: "42.0923",
      lng: "45.4411",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "1624",
      population_proper: "1624"
    },
    {
      city: "Puti",
      lat: "42.0717",
      lng: "43.0947",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1564",
      population_proper: "1564"
    },
    {
      city: "Vartsikhe",
      lat: "42.1439",
      lng: "42.7178",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1559",
      population_proper: "1559"
    },
    {
      city: "Azizkendi",
      lat: "41.4225",
      lng: "44.9453",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "1536",
      population_proper: "1536"
    },
    {
      city: "Khrialeti",
      lat: "42.0061",
      lng: "41.8303",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "1533",
      population_proper: "1533"
    },
    {
      city: "Akhali Atoni",
      lat: "43.0917",
      lng: "40.8000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "1518",
      population_proper: "1518"
    },
    {
      city: "Zovreti",
      lat: "42.1833",
      lng: "43.0408",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1513",
      population_proper: "1513"
    },
    {
      city: "Meria",
      lat: "41.9436",
      lng: "41.8936",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "1494",
      population_proper: "1494"
    },
    {
      city: "Sighnaghi",
      lat: "41.6186",
      lng: "45.9217",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "1485",
      population_proper: "1485"
    },
    {
      city: "Godogani",
      lat: "42.2594",
      lng: "42.7817",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1462",
      population_proper: "1462"
    },
    {
      city: "Chorvila",
      lat: "42.2892",
      lng: "43.4144",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1451",
      population_proper: "1451"
    },
    {
      city: "Kvemo Sarali",
      lat: "41.3411",
      lng: "44.8297",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "1370",
      population_proper: "1370"
    },
    {
      city: "Ganarjiis Mukhuri",
      lat: "42.4253",
      lng: "41.6283",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "1354",
      population_proper: "1354"
    },
    {
      city: "Zeda Simoneti",
      lat: "42.2319",
      lng: "42.9208",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1349",
      population_proper: "1349"
    },
    {
      city: "Anaklia",
      lat: "42.3936",
      lng: "41.5692",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "1331",
      population_proper: "1331"
    },
    {
      city: "Shemokmedi",
      lat: "41.9086",
      lng: "42.0683",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "1322",
      population_proper: "1322"
    },
    {
      city: "Tsageri",
      lat: "42.6472",
      lng: "42.7700",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Rach’a-Lechkhumi da Kvemo Svaneti",
      capital: "minor",
      population: "1320",
      population_proper: "1320"
    },
    {
      city: "Shorapani",
      lat: "42.0956",
      lng: "43.0819",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1258",
      population_proper: "1258"
    },
    {
      city: "Gvishtibi",
      lat: "42.3114",
      lng: "42.5708",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1249",
      population_proper: "1249"
    },
    {
      city: "Baidari",
      lat: "41.4000",
      lng: "44.8833",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "1236",
      population_proper: "1236"
    },
    {
      city: "Natakhtari",
      lat: "41.9194",
      lng: "44.7272",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "",
      population: "1234",
      population_proper: "1234"
    },
    {
      city: "Gurianta",
      lat: "41.9425",
      lng: "41.9578",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "1215",
      population_proper: "1215"
    },
    {
      city: "Ets’eri",
      lat: "42.1983",
      lng: "42.9164",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1206",
      population_proper: "1206"
    },
    {
      city: "Zemo Nat’anebi",
      lat: "41.9658",
      lng: "41.8408",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "1174",
      population_proper: "1174"
    },
    {
      city: "Dvabzu",
      lat: "41.9364",
      lng: "42.0575",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "1171",
      population_proper: "1171"
    },
    {
      city: "Melekeduri",
      lat: "41.9481",
      lng: "42.0239",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "1170",
      population_proper: "1170"
    },
    {
      city: "Marani",
      lat: "42.1583",
      lng: "42.2861",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "1153",
      population_proper: "1153"
    },
    {
      city: "Bandza",
      lat: "42.3489",
      lng: "42.2842",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "1099",
      population_proper: "1099"
    },
    {
      city: "Khelvachauri",
      lat: "41.5856",
      lng: "41.6689",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "1085",
      population_proper: "1085"
    },
    {
      city: "Kvemo Ch’ala",
      lat: "42.0261",
      lng: "44.3950",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "",
      population: "1075",
      population_proper: "1075"
    },
    {
      city: "Ali",
      lat: "42.0872",
      lng: "43.6467",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "",
      population: "1068",
      population_proper: "1068"
    },
    {
      city: "Mukhiani",
      lat: "42.1956",
      lng: "42.5928",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "1058",
      population_proper: "1058"
    },
    {
      city: "Bokhvauri",
      lat: "41.9242",
      lng: "42.0358",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "1056",
      population_proper: "1056"
    },
    {
      city: "Likhauri",
      lat: "41.8806",
      lng: "42.0056",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "952",
      population_proper: "952"
    },
    {
      city: "Abastumani",
      lat: "41.7525",
      lng: "42.8319",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "",
      population: "937",
      population_proper: "937"
    },
    {
      city: "Abastumani",
      lat: "42.4075",
      lng: "41.8686",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "920",
      population_proper: "920"
    },
    {
      city: "Kveda Dzimiti",
      lat: "41.9939",
      lng: "42.0589",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "885",
      population_proper: "885"
    },
    {
      city: "Motsvnari",
      lat: "41.9847",
      lng: "41.8250",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "873",
      population_proper: "873"
    },
    {
      city: "Kirovi",
      lat: "42.4128",
      lng: "41.6700",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "859",
      population_proper: "859"
    },
    {
      city: "Dzveli Abasha",
      lat: "42.2372",
      lng: "42.2136",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "859",
      population_proper: "859"
    },
    {
      city: "Zeda Bakhvi",
      lat: "41.9456",
      lng: "42.1086",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "839",
      population_proper: "839"
    },
    {
      city: "Sarpi",
      lat: "41.5214",
      lng: "41.5519",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "",
      population: "826",
      population_proper: "826"
    },
    {
      city: "Konchkati",
      lat: "41.9781",
      lng: "41.9047",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "805",
      population_proper: "805"
    },
    {
      city: "Kvemo Mak’vaneti",
      lat: "41.9042",
      lng: "42.0183",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "797",
      population_proper: "797"
    },
    {
      city: "Adigeni",
      lat: "41.6750",
      lng: "42.7033",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "minor",
      population: "783",
      population_proper: "783"
    },
    {
      city: "Gaghma Dvabzu",
      lat: "41.9492",
      lng: "42.0669",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "772",
      population_proper: "772"
    },
    {
      city: "Jvari",
      lat: "42.7175",
      lng: "42.0508",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "763",
      population_proper: "763"
    },
    {
      city: "Tkhinvali",
      lat: "41.9639",
      lng: "41.8756",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "733",
      population_proper: "733"
    },
    {
      city: "Naghobilevi",
      lat: "41.9422",
      lng: "41.8667",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "730",
      population_proper: "730"
    },
    {
      city: "Dzveli Khibula",
      lat: "42.4519",
      lng: "41.9806",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "712",
      population_proper: "712"
    },
    {
      city: "Kvachalati",
      lat: "41.8819",
      lng: "42.0186",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "694",
      population_proper: "694"
    },
    {
      city: "Zemo Mak’vaneti",
      lat: "41.8944",
      lng: "42.0389",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "684",
      population_proper: "684"
    },
    {
      city: "Kveda Bakhvi",
      lat: "41.9594",
      lng: "42.0906",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "681",
      population_proper: "681"
    },
    {
      city: "Baghdadi",
      lat: "41.9333",
      lng: "42.1000",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "678",
      population_proper: "678"
    },
    {
      city: "Khvarbeti",
      lat: "41.9536",
      lng: "41.9117",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "673",
      population_proper: "673"
    },
    {
      city: "Kvakhchiri",
      lat: "42.2058",
      lng: "42.7339",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "647",
      population_proper: "647"
    },
    {
      city: "Khojorni",
      lat: "41.2278",
      lng: "44.6903",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "635",
      population_proper: "635"
    },
    {
      city: "Oni",
      lat: "42.5839",
      lng: "43.4417",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Rach’a-Lechkhumi da Kvemo Svaneti",
      capital: "minor",
      population: "626",
      population_proper: "626"
    },
    {
      city: "Tsikhisperdi",
      lat: "41.9578",
      lng: "41.9414",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "610",
      population_proper: "610"
    },
    {
      city: "Akhkerpi",
      lat: "41.2192",
      lng: "44.5764",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "610",
      population_proper: "610"
    },
    {
      city: "Vakijvari",
      lat: "41.9172",
      lng: "42.1453",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "597",
      population_proper: "597"
    },
    {
      city: "Tsitelmta",
      lat: "41.9128",
      lng: "42.0450",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "591",
      population_proper: "591"
    },
    {
      city: "Nasamkhrali",
      lat: "41.9169",
      lng: "45.5408",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "576",
      population_proper: "576"
    },
    {
      city: "Boriti",
      lat: "42.1128",
      lng: "43.2700",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "557",
      population_proper: "557"
    },
    {
      city: "Niabauri",
      lat: "41.8642",
      lng: "42.0061",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "553",
      population_proper: "553"
    },
    {
      city: "Tsaghvli",
      lat: "42.1208",
      lng: "43.6972",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "",
      population: "538",
      population_proper: "538"
    },
    {
      city: "Silauri",
      lat: "41.9992",
      lng: "41.9992",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "531",
      population_proper: "531"
    },
    {
      city: "Likhni",
      lat: "43.1433",
      lng: "40.6011",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Abkhazia",
      capital: "",
      population: "524",
      population_proper: "524"
    },
    {
      city: "Vake",
      lat: "41.9867",
      lng: "41.8589",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "504",
      population_proper: "504"
    },
    {
      city: "Chanieti",
      lat: "41.8683",
      lng: "41.9828",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "489",
      population_proper: "489"
    },
    {
      city: "Tkotsa",
      lat: "42.0922",
      lng: "43.7053",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "",
      population: "487",
      population_proper: "487"
    },
    {
      city: "Tskhemliskhidi",
      lat: "41.9258",
      lng: "42.0842",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "446",
      population_proper: "446"
    },
    {
      city: "Samshvilde",
      lat: "41.5161",
      lng: "44.4908",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "443",
      population_proper: "443"
    },
    {
      city: "Skande",
      lat: "42.2639",
      lng: "43.0481",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "434",
      population_proper: "434"
    },
    {
      city: "Mirzaani",
      lat: "41.5633",
      lng: "45.9722",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "433",
      population_proper: "433"
    },
    {
      city: "Gachedili",
      lat: "42.4681",
      lng: "42.3708",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "427",
      population_proper: "427"
    },
    {
      city: "Askana",
      lat: "41.9528",
      lng: "42.1564",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "424",
      population_proper: "424"
    },
    {
      city: "Pampaleti",
      lat: "41.9306",
      lng: "42.1194",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "411",
      population_proper: "411"
    },
    {
      city: "Chala",
      lat: "41.9261",
      lng: "42.0586",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "408",
      population_proper: "408"
    },
    {
      city: "Shrosha",
      lat: "42.1111",
      lng: "43.1711",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "400",
      population_proper: "400"
    },
    {
      city: "Akhalsopeli",
      lat: "41.9750",
      lng: "41.9869",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "400",
      population_proper: "400"
    },
    {
      city: "Chikhori",
      lat: "42.2319",
      lng: "43.0828",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "398",
      population_proper: "398"
    },
    {
      city: "Shroma",
      lat: "41.9886",
      lng: "41.8372",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "392",
      population_proper: "392"
    },
    {
      city: "Ch’q’vishi",
      lat: "42.1253",
      lng: "42.4336",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "376",
      population_proper: "376"
    },
    {
      city: "Gantiadi",
      lat: "41.9797",
      lng: "41.9325",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "373",
      population_proper: "373"
    },
    {
      city: "Nagomari",
      lat: "41.9978",
      lng: "42.1150",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "365",
      population_proper: "365"
    },
    {
      city: "Kvemo Orozmani",
      lat: "41.3064",
      lng: "44.2008",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "",
      population: "361",
      population_proper: "361"
    },
    {
      city: "Kemperi",
      lat: "42.0417",
      lng: "43.6028",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "",
      population: "350",
      population_proper: "350"
    },
    {
      city: "Jumati",
      lat: "42.0100",
      lng: "41.9639",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "345",
      population_proper: "345"
    },
    {
      city: "Gomi",
      lat: "41.8931",
      lng: "42.1014",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "344",
      population_proper: "344"
    },
    {
      city: "Zinobiani",
      lat: "41.8969",
      lng: "45.9331",
      country: "Georgia",
      iso2: "GE",
      admin_name: "K’akheti",
      capital: "",
      population: "337",
      population_proper: "337"
    },
    {
      city: "Bulvani",
      lat: "42.1800",
      lng: "42.2458",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "337",
      population_proper: "337"
    },
    {
      city: "Zeda Uchkhubi",
      lat: "41.9236",
      lng: "42.0972",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "335",
      population_proper: "335"
    },
    {
      city: "Nakhunavo",
      lat: "42.4217",
      lng: "42.3319",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "333",
      population_proper: "333"
    },
    {
      city: "Zeda Dzimiti",
      lat: "42.0086",
      lng: "42.0586",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "330",
      population_proper: "330"
    },
    {
      city: "Dabali Ets’eri",
      lat: "41.9611",
      lng: "42.1444",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "324",
      population_proper: "324"
    },
    {
      city: "Dghnorisa",
      lat: "42.4686",
      lng: "42.8183",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "321",
      population_proper: "321"
    },
    {
      city: "Potskho-Ets’eri",
      lat: "42.7456",
      lng: "42.0381",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "",
      population: "306",
      population_proper: "306"
    },
    {
      city: "Shua Isnari",
      lat: "41.9914",
      lng: "42.0975",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "293",
      population_proper: "293"
    },
    {
      city: "Grigoleti",
      lat: "42.0369",
      lng: "41.7392",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "286",
      population_proper: "286"
    },
    {
      city: "Kviriketi",
      lat: "41.9139",
      lng: "42.0278",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "284",
      population_proper: "284"
    },
    {
      city: "Kakuti",
      lat: "41.8542",
      lng: "41.9708",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "282",
      population_proper: "282"
    },
    {
      city: "Zvare",
      lat: "41.9747",
      lng: "43.4078",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "279",
      population_proper: "279"
    },
    {
      city: "Ubisi",
      lat: "42.0986",
      lng: "43.2242",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Imereti",
      capital: "",
      population: "276",
      population_proper: "276"
    },
    {
      city: "Baileti",
      lat: "41.9769",
      lng: "41.9700",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "274",
      population_proper: "274"
    },
    {
      city: "Mziani",
      lat: "41.9792",
      lng: "42.1583",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Guria",
      capital: "",
      population: "263",
      population_proper: "263"
    },
    {
      city: "Rustavi",
      lat: "42.2897",
      lng: "43.8543",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Kvemo Kartli",
      capital: "admin",
      population: "",
      population_proper: ""
    },
    {
      city: "Keda",
      lat: "41.6009",
      lng: "41.9401",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Kareli",
      lat: "42.0244",
      lng: "43.9011",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Shida Kartli",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Chkhorots’q’u",
      lat: "42.5258",
      lng: "42.1321",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samegrelo-Zemo Svaneti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Khulo",
      lat: "41.6459",
      lng: "42.3146",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Shuakhevi",
      lat: "41.6242",
      lng: "42.1857",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Ajaria",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Asp’indza",
      lat: "41.5739",
      lng: "43.2483",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Samtskhe-Javakheti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Tianeti",
      lat: "42.1083",
      lng: "44.9639",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "St’epants’minda",
      lat: "42.6567",
      lng: "44.6433",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Lent’ekhi",
      lat: "42.7889",
      lng: "42.7223",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Rach’a-Lechkhumi da Kvemo Svaneti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Akhalgori",
      lat: "42.1260",
      lng: "44.4833",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "",
      population_proper: ""
    },
    {
      city: "Java",
      lat: "42.3997",
      lng: "43.9367",
      country: "Georgia",
      iso2: "GE",
      admin_name: "Mtskheta Mtianeti",
      capital: "minor",
      population: "",
      population_proper: ""
    }
  ]